steps:
  # Build the Docker image using the Dockerfile in the prod directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/apt-cycling-433408-v4/repo-trial/hello-world-app:prod-latest', '-f', 'prod/Dockerfile', '.']

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/apt-cycling-433408-v4/repo-trial/hello-world-app:prod-latest']

  # Get GKE credentials for the prod cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cluster-prod --zone us-central1 --project apt-cycling-433408-v4

  # Step 4: Deploy the updated image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'prod/deployment-prod.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-prod'

  # Step 5: Apply the Kubernetes service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'prod/service-prod.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-prod'
  
  # # Deploy the updated image to GKE
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'prod/deployment-prod.yaml']

  # # Apply the Kubernetes service
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'prod/service-prod.yaml']

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE
  machine_type: 'E2_HIGHCPU_8'

