steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'preprod/Dockerfile.preprod', '-t', 'us-central1-docker.pkg.dev/brave-tea-431307-a2/my-repo/hello-world-app:preprod', 'preprod/']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/brave-tea-431307-a2/my-repo/hello-world-app:preprod']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'preprod/deployment-preprod.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CORE_PROJECT=brave-tea-431307-a2'
options:
  logging: CLOUD_LOGGING_ONLY

