steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/my-project-433308/repo-trial/hello-world-app:prod-latest', '-f', 'prod/Dockerfile.prod', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/my-project-433308/repo-trial/hello-world-app:prod-latest']
images:
- 'us-central1-docker.pkg.dev/my-project-433308/repo-trial/hello-world-app:prod-latest'

options:
  logging: CLOUD_LOGGING_ONLY
