steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/brave-tea-431307-a2/repo-trial/hello-world-preprod:latest', '.']
    dir: 'preprod'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/brave-tea-431307-a2/repo-trial/hello-world-preprod:latest']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'preprod/deployment-preprod.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'preprod/service-preprod.yaml']

options:
  logging: CLOUD_LOGGING_ONLY
