apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service-prod
spec:
  selector:
    app: hello-world-app-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
